remote_theme: pmarsceill/just-the-docs
markdown: kramdown
title: SlimeVR Documentation
description: Building your own trackers, updating firmware, installing the SlimeVR server and using phones as trackers
footer_content: "SlimeVR is created under an MIT License<br><strong>Github Repo: </strong><a href='https://github.com/SlimeVR/SlimeVR-Server'>https://github.com/SlimeVR/SlimeVR-Server</a><br><strong>Docs Github Repo: </strong><a href='https://github.com/SlimeVR/SlimeVR-Docs-Site'>https://github.com/SlimeVR/SlimeVR-Docs-Site</a><br><strong>Discord: </strong><a href='https://discord.gg/SlimeVR'>https://discord.gg/SlimeVR</a>"
